### ISSUE TITLE
Add prebuilt docker image

### ISSUE THREAD

**Issue by edvinerikson** [papyon-apps/appload#2]
It would be nice if an github action could upload a docker image to github registry on each release/commit.

**Comment by bufgix** [comment]
+1 I have planned this improvement

**Comment by bufgix** [comment]
Hey @edvinerikson 

I just created prebuild docker image. You can use this image with following command

```bash
docker run -d -p 3005:3000 -e HOST="http://localhost:3005"  -v ./uploads:/app/uploads papyonlab/appload
```
